services:
  db:
    build: ./dataBase
    container_name: dataBase_RetoFactus
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.123
      POSTGRES_DB: retoFactus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d retoFactus"]
      interval: 10s
      timeout: 15s
      retries: 5

  api:
    build: ./api
    container_name: Api_RetoFactus
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin.123
      - DB_DATABASE=retoFactus
      - JWT_ACCESS_SECRET="your_JWT_ACCESS_SECRET"
      - LIMIT_REQUESTS=50
      - TTL_REQUESTS_LOGIN=60000
      - BLOCK_DURATION=60000
      - LIMIT_REQUESTS_LOGIN=5
      - TTL_REQUESTS_LOGIN=60000
      - BLOCK_DURATION_LOGIN=600000
    ports:
      - "4000:4000"
    volumes:
      - ./api/src:/app/api/src # Solo monta el c√≥digo fuente
      - ./api/package.json:/app/api/package.json # Monta package.json
      - ./api/yarn.lock:/app/api/yarn.lock # Monta yarn.lock
    restart: unless-stopped
    command: yarn start:dev # Usar comando de desarrollo

  web:
    build: ./frontend
    container_name: Web_RetoFactus
    ports:
      - "3000:3000"

volumes:
  postgres_data:
